theme: jekyll-theme-cayman
title: AGI Russia
banner: "https://agirussia.github.io/img/AGI%20RUS-02.jpg"
description: Ресурсы русскоязычного сообщества разработчиков общего или сильного искусственного интеллекта AGI
